// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DEManagement.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::kuber;

class DEManagementHandler : virtual public DEManagementIf {
 public:
  DEManagementHandler() {
    // Your initialization goes here
  }

  int32_t add_dmEngine(const std::string& name, const std::string& fileName, const int32_t port) {
    // Your implementation goes here
    printf("add_dmEngine\n");
  }

  int32_t remove_dmEngine(const std::string& name) {
    // Your implementation goes here
    printf("remove_dmEngine\n");
  }

  int32_t describe_dmEngine(const std::string& name) {
    // Your implementation goes here
    printf("describe_dmEngine\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<DEManagementHandler> handler(new DEManagementHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new DEManagementProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

