/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kuber_constants.h"

namespace kuber {

const kuberConstants g_kuber_constants;

kuberConstants::kuberConstants() {
}

} // namespace

