/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kuber_CONSTANTS_H
#define kuber_CONSTANTS_H

#include "kuber_types.h"

namespace kuber {

class kuberConstants {
 public:
  kuberConstants();

};

extern const kuberConstants g_kuber_constants;

} // namespace

#endif
